name: tfsec

on: [push]

env:
  TF_VERSION: 0.14.8
  TFSEC_VERSION: v0.39.25

jobs:
  tfsec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Terraform security scan
        uses: triat/terraform-security-scan@v2.2.1
        env:
          tfsec_version: ${{ env.TFSEC_VERSION }}
